---
title: Foo
timezone: UTC
collections:
  pics:
    title: Pics
    output: true
    Field name:
      Key 1: path_image
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.'

baseurl: 
url: 
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
prose:
  siteurl: https://anselmi-tuhkanen2.github.io/
  media: media
